<Weapon>
	<hp>100</hp>
	<maxHp>100</maxHp>
	<armor>10</armor>
	<damage>1</damage>
	<attackSpeed>100</attackSpeed>
	<projectileName>PROJ-02</projectileName>
	<type>WEAPON</type>
	<weaponType>ROCKET_LAUNCHER</weaponType>
	<slot>0</slot>
	<weight>100</weight>
	<name>SCA-01D</name>
	<description>SCA-01 Default Weapon</description>
	<price>150</price>
	<maxStack>1</maxStack>
	<stack>1</stack>
</Weapon>
